# -*- coding: utf-8 -*-
"""locationdetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ekk9udK047uoRboC4YSdLAuqeKZzgOxw
"""

import geocoder
g = geocoder.ip('me')
print(g.latlng)

import googlemaps
from datetime import datetime
key='AIzaSyBpGtkmJSz7_PJSvT8LOGXVKZNmoPZsXCM'
gmaps = googlemaps.Client(key)

import pandas as pd
import requests
import json

lat=str(g.latlng[0])
longi=str(g.latlng[1])
url="https://maps.googleapis.com/maps/api/place/nearbysearch/json?location="+lat+","+long+"&radius=5000&keyword=reststop&key="+key
response = requests.get(url).json()
print(response)

address=[response['results'][0]['geometry']['location']['lat'],response['results'][0]['geometry']['location']['lng']]

url="https://maps.googleapis.com/maps/api/directions/json?origin="+lat+","+longi+"&destination="+str(address[0])+","+str(address[1])+"&key="+key
response = requests.get(url).json()
print(response)

print(response.keys())
print(response['geocoded_waypoints'])

print(response['routes'][0])
print(response['routes'][0].keys())
print(response['routes'][0]['legs'])
print(response['routes'][0]['legs'][0])
print(response['routes'][0]['legs'][0]['distance'])
distance=response['routes'][0]['legs'][0]['distance']['text']
duration=response['routes'][0]['legs'][0]['duration']['text']
end_address=response['routes'][0]['legs'][0]['end_address']
start_address=response['routes'][0]['legs'][0]['start_address']
print(distance)
print(duration)
print(end_address)
print(start_address)
distancelist=[]
durationlist=[]
html_instructions_list=[]
maneuver_list=[]
for i in response['routes'][0]['legs'][0]['steps']:
  print(i.keys())
  distancelist.append(i['distance']['text'])
  durationlist.append(i['duration']['text'])
  html_instructions_list.append(i['html_instructions'])
print(distancelist)
print(html_instructions_list)

